# Fly.io deployment configuration for AI Marketing Creators Backend
app = "ai-marketing-creators"
primary_region = "sjc"  # San Jose, California

# Build configuration
[build]
  dockerfile = "Dockerfile"

# Environment variables
[env]
  PORT = "8080"
  NODE_ENV = "production"

# HTTP service configuration
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  # Health check configuration
  [http_service.checks]
    [http_service.checks.alive]
      type = "http"
      method = "GET"
      path = "/health"
      interval = "30s"
      timeout = "5s"
      grace_period = "10s"

# Virtual machine configuration
[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

# Volume mounts (if you need persistent storage)
# [[mounts]]
#   source = "data"
#   destination = "/app/data"

# Process configuration
[processes]
  app = "npm start"
  worker = "npm run workers"  # If you want to run workers separately

# Deployment configuration
[deploy]
  release_command = "echo 'Deployment starting...'"

# Secrets needed (set these in Fly.io dashboard or via CLI)
# These are NOT included in this file for security
# Required secrets:
# - MONGODB_URI
# - OPENAI_API_KEY
# - ELEVENLABS_API_KEY
# - REPLICATE_API_KEY
# - STABILITY_API_KEY
# - JWT_SECRET
# - PAYPAL_CLIENT_ID
# - PAYPAL_CLIENT_SECRET
